# ~/.config/starship.toml

# Use custom format
format = '''
[┌───────────────────>](bold green)$hostname
[│](bold green)$directory$git_branch$git_commit$git_state$git_status$rust$python$lua$package
[└─>](bold green) '''


######### Right Prompt  ################
##A minimal left prompt
# format = """$character"""
# 
##move the rest of the prompt to the right
# right_format = """$all"""
########################################

######## Continuation Prompt ##########
# A continuation prompt that displays two filled-in arrows
continuation_prompt = '▶▶ '
#######################################


# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Set 'foo' as custom color palette
palette = 'foo'

# Define custom colors
[palettes.foo]
# Overwrite existing color
blue = '21'
# Define new color
mustard = '#af8700'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
